# Generated by Django 3.2.7 on 2021-10-13 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notes',
            name='description',
        ),
        migrations.RemoveField(
            model_name='notes',
            name='title',
        ),
    ]
