# Generated by Django 3.2.7 on 2021-10-13 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20211013_0934'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notes',
        ),
    ]
